### PR TITLE
(interpreter) #124 Bug fix: calling methods in expr mode was broken in REPL

### LINKED ISSUE #124: Cannot call user-defined method without trailing semicolon in REPL
I just discovered today that this doesn't work as expected:

```
Perlang Interactive REPL Console (0.1.0-dev.103, built from ff7111d)
> fun hello(): void { print 1; }
> hello()
[line 1] Error at 'hello': Attempting to call undefined function 'hello'
> hello();
1
```

Interestingly enough though, these _do_ work. But remember that `print` is not a built-in function but a reserved word in the language for now:

```
Perlang Interactive REPL Console (0.1.0-dev.103, built from ff7111d)
> print 1
1
> print "hej"
hej
```

Calling .NET-native functions like `Base64.encode` works. I think the problem here is specifically referring to user-defined functions.

### PR DESCRIPTION
**Pull request by perlun**
This turned out to be quite easy in the end; for a change, I realized fairly quickly that the problem was that we special-cased expressions in an unhealthy way in `Perlang.Interpreter.PerlangInterpreter.Eval()`. Will write more in the diff view in a minute.

Closes #124.

### CODE REVIEW

File: Perlang.Interpreter/Immutability/ImmutabilityValidator.cs [hunk 1]
```diff
@@ -22,14 +22,6 @@ internal class ImmutabilityValidator : VisitorBase
...
         }
 
-        public static void Validate(
-            Expr expr,
-            Action<ValidationError> immutabilityValidationErrorCallback,
-            Func<Expr, Binding?> getVariableOrFunctionBinding)
-        {
-            new ImmutabilityValidator(immutabilityValidationErrorCallback, getVariableOrFunctionBinding).Visit(expr);
-        }
-
```
Comment (perlun) [inline Perlang.Interpreter/Immutability/ImmutabilityValidator.cs:32]: :tada: No need for this any more now since we unified all immutability validation to use the overload which takes a `List<Stmt>` parameter.

File: Perlang.Interpreter/PerlangInterpreter.cs [hunk 2]
```diff
@@ -365,6 +372,12 @@ private void RegisterGlobalClasses()
                     GetVariableOrFunctionBinding
                 );
 
+                // All validation was successful, but unlike for statements, there is no need to mutate the
+                // previousStatements field in this case. Think about it for a moment. We know that the line being
+                // interpreted is an expression, so it _cannot_ have declared any new variable or anything like that
+                // (those are only allowed in statements). Hence, we presume that this expression is, if you will,
+                // "side-effect-free" in that sense.
+
```
Comment (perlun) [inline Perlang.Interpreter/PerlangInterpreter.cs:380]: The hunks for this file is the critical part of this PR. We simply _must_ use the information in the previous statement, together with the expression given in the new statement to be able to properly perform all validations. :point_up: is where the bug was that caused this problem.

File: Perlang.Interpreter/Typing/TypeValidator.cs [hunk 3]
```diff
@@ -80,66 +80,6 @@ internal static class TypeValidator
...
-
-            // The whole expression tree should be walked by now; any type references still not resolved at this point
-            // is a critical error that should fail the type validation. To provide as much information to the user
-            // as possible, the full list errors (if any) are reported back to the caller; we don't just stop at the
-            // first error encountered. (The compiler could potentially discard information except for the first n
-            // errors if desired, though. The key point here is to not discard it at the wrong stage in the pipeline.)
-            new TypeValidatorHelper(getVariableOrFunctionCallback, typeValidationErrorCallback)
-                .ReportErrors(expr);
-        }
-
```
Comment (perlun) [inline Perlang.Interpreter/Typing/TypeValidator.cs:142]: :rocket: Again, nice to be able to remove some code now that "everything is a statement". :joy:
