### PR TITLE
(interpreter) Fix ICE for ClrType unexpectedly null

### LINKED ISSUE #239: Error at 'get_type': Internal compiler error: ClrType for '#<Identifier i>' was unexpectedly null.
Seen with 07e281c, the expression below gives the following _compile-time_ error:

```
Perlang Interactive REPL Console (0.1.0-dev.188, built from git commit 07e281c)
> var i: NonexistentType = 1; i++; print i.get_type()
[line 1] Error at 'get_type': Internal compiler error: ClrType for '#<Identifier i>' was unexpectedly null.
```

Older commits like ce4c816cb34d220ab29e224d626e80702324dc2e exhibit a slightly different behavior. This is because a `null` check got added in https://github.com/perlang-org/perlang/pull/236/files#diff-e6936507ddb8e2541d15c233a4a211e6eecf7e88a3e213b923fbdbc275659ce5R306, emitting the ICE above in case the type is `null`.

```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Perlang.Interpreter.Typing.TypeResolver.VisitGetExpr(Get expr) in /home/per/git/perlang/src/Perlang.Interpreter/Typing/TypeResolver.cs:line 317
   at Perlang.Expr.Get.Accept[TR](IVisitor`1 visitor) in /home/per/git/perlang/src/Perlang.Common/Expr.cs:line 318
   at Perlang.VisitorBase.Visit(Expr expr) in /home/per/git/perlang/src/Perlang.Common/VisitorBase.cs:line 33
   at Perlang.Interpreter.Typing.TypeResolver.VisitCallExpr(Call expr) in /home/per/git/perlang/src/Perlang.Interpreter/Typing/TypeResolver.cs:line 163
   at Perlang.Expr.Call.Accept[TR](IVisitor`1 visitor) in /home/per/git/perlang/src/Perlang.Common/Expr.cs:line 146
   at Perlang.VisitorBase.Visit(Expr expr) in /home/per/git/perlang/src/Perlang.Common/VisitorBase.cs:line 33
   at Perlang.VisitorBase.VisitPrintStmt(Print stmt) in /home/per/git/perlang/src/Perlang.Common/VisitorBase.cs:line 176
   at Perlang.Stmt.Print.Accept[TR](IVisitor`1 visitor) in /home/per/git/perlang/src/Perlang.Common/Stmt.cs:line 128
   at Perlang.VisitorBase.Visit(Stmt stmt) in /home/per/git/perlang/src/Perlang.Common/VisitorBase.cs:line 28
   at Perlang.VisitorBase.Visit(IEnumerable`1 statements) in /home/per/git/perlang/src/Perlang.Common/VisitorBase.cs:line 22
   at Perlang.Interpreter.Typing.TypeResolver.Resolve(IList`1 statements) in /home/per/git/perlang/src/Perlang.Interpreter/Typing/TypeResolver.cs:line 40
   at Perlang.Interpreter.Typing.TypeValidator.Validate(IList`1 statements, Action`1 typeValidationErrorCallback, Func`2 getVariableOrFunctionCallback, Action`1 compilerWarningCallback) in /home/per/git/perlang/src/Perlang.Interpreter/Typing/TypeValidator.cs:line 48
   at Perlang.Interpreter.PerlangInterpreter.Eval(String source, ScanErrorHandler scanErrorHandler, ParseErrorHandler parseErrorHandler, NameResolutionErrorHandler nameResolutionErrorHandler, ValidationErrorHandler typeValidationErrorHandler, ValidationErrorHandler immutabilityValidationErrorHandler, CompilerWarningHandler compilerWarningHandler) in /home/per/git/perlang/src/Perlang.Interpreter/PerlangInterpreter.cs:line 225
   at Perlang.ConsoleApp.Program.Run(String source, CompilerWarningHandler compilerWarningHandler) in /home/per/git/perlang/src/Perlang.ConsoleApp/Program.cs:line 352
   at Perlang.ConsoleApp.Program.<>c__DisplayClass9_0.<MainWithCustomConsole>b__3(ParseResult parseResult, IConsole console) in /home/per/git/perlang/src/Perlang.ConsoleApp/Program.cs:line 156
```

### PR DESCRIPTION
**Pull request by perlun**
This fixes one of the last-standing (known) bugs before we can carve out the 0.1.0 release. It feels like it's about time, after about 2 years of development without a single "release". :slightly_smiling_face: (only snapshot builds for each commit)

Closes #239

### CODE REVIEW

File: src/Perlang.Interpreter/Typing/TypesResolvedValidator.cs [hunk 1]
```diff
@@ -1,3 +1,4 @@
+#nullable enable
```
Comment (perlun) [inline src/Perlang.Interpreter/Typing/TypesResolvedValidator.cs:1]: (Drive-by fix which enables #39 for this file. There were actually some `null`-related issues with it. We should really aim for enabling this for the whole project within the 0.2.0 release cycle.)

File: src/Perlang.Interpreter/Typing/TypesResolvedValidator.cs [hunk 2]
```diff
@@ -355,28 +378,19 @@ public override VoidObject VisitVarStmt(Stmt.Var stmt)
                     }
                 }
             }
-            else if (stmt.Initializer == null)
+            else if (!stmt.TypeReference.ExplicitTypeSpecified && stmt.Initializer == null)
             {
                 TypeValidationErrorCallback(new TypeValidationError(
-                    null,
+                    stmt.Name,
```
Comment (perlun) [inline src/Perlang.Interpreter/Typing/TypesResolvedValidator.cs:384]: This is one of the problems referred to in this comment: https://github.com/perlang-org/perlang/pull/279/files#r809233300. The previous way this was written would cause runtime errors in the `Perlang.ConsoleApp.Program.Error` method. Particularly nasty, since _these errors are typically not provoked by tests_. Needless to say, this is just one example of why doing #39 sooner than later would be a Really Good Thing.&trade;

File: src/Perlang.Interpreter/Typing/TypesResolvedValidator.cs [hunk 3]
```diff
@@ -355,28 +378,19 @@ public override VoidObject VisitVarStmt(Stmt.Var stmt)
                     }
                 }
             }
-            else if (stmt.Initializer == null)
+            else if (!stmt.TypeReference.ExplicitTypeSpecified && stmt.Initializer == null)
```
Comment (perlun) [inline src/Perlang.Interpreter/Typing/TypesResolvedValidator.cs:381]: (This fixes a bug. With other changes in this PR, we would sometimes get into this branch when an explicit type was set _but the type did not exist_. In other words, `ExplicitTypeSpecified` would be `true` but `IsResolved` would be false. The fix here is the right thing - we should only produce errors about type inference when type inference is attempted, of course... :see_no_evil:)

File: src/Perlang.Interpreter/Typing/TypesResolvedValidator.cs [hunk 4]
```diff
@@ -355,28 +378,19 @@ public override VoidObject VisitVarStmt(Stmt.Var stmt)
...
             }
-            else if (!stmt.TypeReference.ExplicitTypeSpecified)
-            {
-                // FIXME: Let's see if we'll ever go into this branch. If we don't have a test that reproduces
-                // this once all tests are green, we should consider wiping it from the face off the earth.
-                TypeValidationErrorCallback(new TypeValidationError(
-                    null,
-                    $"Failed to infer type for variable '{stmt.Name.Lexeme}' from usage. Try specifying the type explicitly."
-                ));
-            }
```
Comment (perlun) [inline src/Perlang.Interpreter/Typing/TypesResolvedValidator.cs:374]: It was time to "[wipe] it from the face off the earth" now. :smiling_imp:

File: src/Perlang.Tests.Integration/Typing/TypingTests.cs [hunk 5]
```diff
@@ -416,7 +416,38 @@ public void function_return_value_detects_invalid_assignment_to_variable_of_anot
...
-            Assert.Equal("Cannot assign string to int variable", exception.Message);
+            Assert.Equal("Cannot assign string to int variable", exception!.Message);
+        }
+
+        [Fact]
+        public void var_of_non_existent_type_with_initializer_emits_expected_error()
+        {
+            // TODO: I have a feeling that this somehow incorrectly infers the type from the 1 integer to some parts of
+            // the parsed syntax tree (since NonexistentType does not exist). Investigate this someday, since it could
+            // lead to subtle, very hard-to-track bugs.
```
Comment (perlun) [inline src/Perlang.Tests.Integration/Typing/TypingTests.cs:427]: ...in a later PR.
