### PR TITLE
(consoleapp) Fix exception in mintty-based shells on Windows

### LINKED ISSUE #107: Improve Windows installation experience
Our current download instructions at https://perlang.org/download/ suggests the usage of Git Bash on Windows. Well, too bad it doesn't really work _at all_ after installation in that shell though. 😒 

Interestingly enough, it works pretty fine in a regular `cmd.exe` window after installation though, so I think it would be pretty much enough at this stage to:

- [x] Improve the instructions on the web page to make this a "known limitation" of the current setup.
- [ ] Detect the fact that input is redirected and never even try to read keys from the console in that case. (If we really want to be kind, we could suggest the usage of `cmd.exe` on Windows instead of Git Bash.)

Worth mentioning is that things seem to work nicely in WSL, though.

```shell
$ $HOME/.perlang/nightly/bin/perlang
Perlang Interactive REPL Console (0.1.0+b67d337)
> Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at System.ReadLine.GetText(KeyHandler keyHandler)
   at System.ReadLine.Read(String prompt, String default)
   at Perlang.ConsoleApp.Program.RunPrompt()
   at Perlang.ConsoleApp.Program.<>c.<Main>b__6_0(ParseResult parseResult, IConsole console)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### PR DESCRIPTION
**Pull request by perlun**
I had thought about this for some day(s), and decided to give it a look. The fact that `winpty` exists surely makes this a whole lot easier to "fix", even though it's a bit of a workaround. It does make Perlang much more accessible for people who are locked inside their Windows, so that makes this a noteworthy fix. 😛 

Closes #107

### CODE REVIEW

File: src/Perlang.ConsoleApp/Program.cs [hunk 1]
```diff
@@ -201,7 +205,7 @@ public static int MainWithCustomConsole(string[] args, IConsole console)
                             replMode: true,
                             standardOutputHandler: console.Out.WriteLine,
                             disabledWarningsAsErrors: disabledWarningsAsErrorsList
-                        ).RunPrompt();
+                        ).RunPrompt(args);
```
Comment (perlun) [inline src/Perlang.ConsoleApp/Program.cs:208]: (`args` is typically empty in these cases, but it doesn't hurt to provide it to future-proof in case it will be non-empty sometime in the future.)
