### PR TITLE
(scripts) Use a correct approach for getting git commit

### LINKED ISSUE #292: GIT_COMMIT gets set incorrectly for tagged commits
After the recent [0.1.0 release](https://github.com/perlang-org/perlang/releases/tag/v0.1.0), it was discovered that `GIT_COMMIT` in `scripts/update_common_constants.rb` does not get set correctly when the latest commit is also tagged. This gives the following result in the generated binary:

```
$ "$HOME/.perlang/release/bin/perlang" -V
Perlang 0.1.0 (built from git commit v0.1.0) on .NET 6.0.2

  Number of detected (v)CPUs: 8
  Running in 64-bit mode: True
  Operating system info: Unix 5.10.0.10
```

### PR DESCRIPTION
**Pull request by perlun**
Fixes #292.

### CODE REVIEW

File: scripts/update_common_constants.rb [hunk 1]
```diff
@@ -15,7 +15,7 @@
 GIT_DESCRIBE_VERSION = CUSTOM_VERSION || `git describe --tags | sed s%^dev/%% | sed s/-g.*$// | sed -E "s/-([0-9]*)$/-dev.\\1/"`.rstrip
 GIT_DESCRIBE_VERSION.sub!(%r{^v}, '')
 
-GIT_COMMIT = `git describe --always`.rstrip
+GIT_COMMIT = `git rev-parse --short HEAD`.rstrip
```
Comment (perlun) [inline scripts/update_common_constants.rb:18]: The previous approach doesn't work correctly on tagged commits. The new approach was suggested here on SO: https://stackoverflow.com/questions/949314/how-to-retrieve-the-hash-for-the-current-commit-in-git#comment17766441_949391
